apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carworth

resources:
  - ../../base

images:
  - name: carworth
    newName: us-east1-docker.pkg.dev/lineten/lineten-dev/carworth
    newTag: latest  # Updated by CI/CD with commit SHA
