apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: carworth-frontend
spec:
  sslPolicy: null
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
