apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carworth
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: carworth-ip
    networking.gke.io/v1beta1.FrontendConfig: carworth-frontend
    networking.gke.io/certificate-map: carworth-cert-map
spec:
  defaultBackend:
    service:
      name: carworth
      port:
        number: 80
  rules:
    - host: carworth.b0lt.foo
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: carworth
                port:
                  number: 80
