apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recall-app
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: recall-app-ip
spec:
  defaultBackend:
    service:
      name: recall-app
      port:
        number: 80
