apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recall-app
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: recall-app-ip
    networking.gke.io/v1beta1.FrontendConfig: recall-app-frontend
    networking.gke.io/certificate-map: recall-app-cert-map
spec:
  tls:
    - hosts:
        - recall.b0lt.foo
  defaultBackend:
    service:
      name: recall-app
      port:
        number: 80
  rules:
    - host: recall.b0lt.foo
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: recall-app
                port:
                  number: 80
