apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recall-app

resources:
  - ../../base

images:
  - name: recall-app
    newName: us-east1-docker.pkg.dev/lineten/lineten-dev/recall-app
    newTag: fddeb304c2eee7d0511c8020f9eddeb6540ad2ab  # Updated by CI/CD with commit SHA
